package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.ambient.BatModel;
import net.minecraft.client.model.animal.allay.AllayModel;
import net.minecraft.client.model.animal.armadillo.ArmadilloModel;
import net.minecraft.client.model.animal.axolotl.AxolotlModel;
import net.minecraft.client.model.animal.bee.BeeModel;
import net.minecraft.client.model.animal.bee.BeeStingerModel;
import net.minecraft.client.model.animal.camel.CamelModel;
import net.minecraft.client.model.animal.camel.CamelSaddleModel;
import net.minecraft.client.model.animal.chicken.ChickenModel;
import net.minecraft.client.model.animal.chicken.ColdChickenModel;
import net.minecraft.client.model.animal.cow.ColdCowModel;
import net.minecraft.client.model.animal.cow.CowModel;
import net.minecraft.client.model.animal.cow.WarmCowModel;
import net.minecraft.client.model.animal.dolphin.DolphinModel;
import net.minecraft.client.model.animal.equine.AbstractEquineModel;
import net.minecraft.client.model.animal.equine.DonkeyModel;
import net.minecraft.client.model.animal.equine.EquineSaddleModel;
import net.minecraft.client.model.animal.feline.CatModel;
import net.minecraft.client.model.animal.feline.FelineModel;
import net.minecraft.client.model.animal.fish.CodModel;
import net.minecraft.client.model.animal.fish.PufferfishBigModel;
import net.minecraft.client.model.animal.fish.PufferfishMidModel;
import net.minecraft.client.model.animal.fish.PufferfishSmallModel;
import net.minecraft.client.model.animal.fish.SalmonModel;
import net.minecraft.client.model.animal.fish.TropicalFishLargeModel;
import net.minecraft.client.model.animal.fish.TropicalFishSmallModel;
import net.minecraft.client.model.animal.fox.FoxModel;
import net.minecraft.client.model.animal.frog.FrogModel;
import net.minecraft.client.model.animal.frog.TadpoleModel;
import net.minecraft.client.model.animal.ghast.HappyGhastHarnessModel;
import net.minecraft.client.model.animal.ghast.HappyGhastModel;
import net.minecraft.client.model.animal.goat.GoatModel;
import net.minecraft.client.model.animal.golem.CopperGolemModel;
import net.minecraft.client.model.animal.golem.IronGolemModel;
import net.minecraft.client.model.animal.golem.SnowGolemModel;
import net.minecraft.client.model.animal.llama.LlamaModel;
import net.minecraft.client.model.animal.llama.LlamaSpitModel;
import net.minecraft.client.model.animal.nautilus.NautilusArmorModel;
import net.minecraft.client.model.animal.nautilus.NautilusModel;
import net.minecraft.client.model.animal.nautilus.NautilusSaddleModel;
import net.minecraft.client.model.animal.panda.PandaModel;
import net.minecraft.client.model.animal.parrot.ParrotModel;
import net.minecraft.client.model.animal.pig.ColdPigModel;
import net.minecraft.client.model.animal.pig.PigModel;
import net.minecraft.client.model.animal.polarbear.PolarBearModel;
import net.minecraft.client.model.animal.rabbit.RabbitModel;
import net.minecraft.client.model.animal.sheep.SheepFurModel;
import net.minecraft.client.model.animal.sheep.SheepModel;
import net.minecraft.client.model.animal.sniffer.SnifferModel;
import net.minecraft.client.model.animal.squid.SquidModel;
import net.minecraft.client.model.animal.turtle.TurtleModel;
import net.minecraft.client.model.animal.wolf.WolfModel;
import net.minecraft.client.model.effects.EvokerFangsModel;
import net.minecraft.client.model.effects.SpinAttackEffectModel;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.model.monster.blaze.BlazeModel;
import net.minecraft.client.model.monster.breeze.BreezeModel;
import net.minecraft.client.model.monster.creaking.CreakingModel;
import net.minecraft.client.model.monster.creeper.CreeperModel;
import net.minecraft.client.model.monster.dragon.EnderDragonModel;
import net.minecraft.client.model.monster.enderman.EndermanModel;
import net.minecraft.client.model.monster.endermite.EndermiteModel;
import net.minecraft.client.model.monster.ghast.GhastModel;
import net.minecraft.client.model.monster.guardian.GuardianModel;
import net.minecraft.client.model.monster.hoglin.HoglinModel;
import net.minecraft.client.model.monster.illager.IllagerModel;
import net.minecraft.client.model.monster.nautilus.ZombieNautilusCoralModel;
import net.minecraft.client.model.monster.phantom.PhantomModel;
import net.minecraft.client.model.monster.piglin.PiglinModel;
import net.minecraft.client.model.monster.ravager.RavagerModel;
import net.minecraft.client.model.monster.shulker.ShulkerModel;
import net.minecraft.client.model.monster.silverfish.SilverfishModel;
import net.minecraft.client.model.monster.skeleton.BoggedModel;
import net.minecraft.client.model.monster.skeleton.SkeletonModel;
import net.minecraft.client.model.monster.slime.MagmaCubeModel;
import net.minecraft.client.model.monster.slime.SlimeModel;
import net.minecraft.client.model.monster.spider.SpiderModel;
import net.minecraft.client.model.monster.strider.StriderModel;
import net.minecraft.client.model.monster.vex.VexModel;
import net.minecraft.client.model.monster.warden.WardenModel;
import net.minecraft.client.model.monster.witch.WitchModel;
import net.minecraft.client.model.monster.wither.WitherBossModel;
import net.minecraft.client.model.monster.zombie.DrownedModel;
import net.minecraft.client.model.monster.zombie.ZombieVillagerModel;
import net.minecraft.client.model.npc.VillagerModel;
import net.minecraft.client.model.object.armorstand.ArmorStandArmorModel;
import net.minecraft.client.model.object.armorstand.ArmorStandModel;
import net.minecraft.client.model.object.banner.BannerFlagModel;
import net.minecraft.client.model.object.banner.BannerModel;
import net.minecraft.client.model.object.bell.BellModel;
import net.minecraft.client.model.object.boat.BoatModel;
import net.minecraft.client.model.object.boat.RaftModel;
import net.minecraft.client.model.object.book.BookModel;
import net.minecraft.client.model.object.cart.MinecartModel;
import net.minecraft.client.model.object.chest.ChestModel;
import net.minecraft.client.model.object.crystal.EndCrystalModel;
import net.minecraft.client.model.object.equipment.ElytraModel;
import net.minecraft.client.model.object.equipment.ShieldModel;
import net.minecraft.client.model.object.leash.LeashKnotModel;
import net.minecraft.client.model.object.projectile.ArrowModel;
import net.minecraft.client.model.object.projectile.ShulkerBulletModel;
import net.minecraft.client.model.object.projectile.TridentModel;
import net.minecraft.client.model.object.projectile.WindChargeModel;
import net.minecraft.client.model.object.skull.DragonHeadModel;
import net.minecraft.client.model.object.skull.PiglinHeadModel;
import net.minecraft.client.model.object.skull.SkullModel;
import net.minecraft.client.model.player.PlayerCapeModel;
import net.minecraft.client.model.player.PlayerEarsModel;
import net.minecraft.client.model.player.PlayerModel;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.ArmorModelSet;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class LayerDefinitions {
    private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);
    private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);
    private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);

    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        Builder<ModelLayerLocation, LayerDefinition> builder = ImmutableMap.builder();
        LayerDefinition layerdefinition = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
        ArmorModelSet<LayerDefinition> armormodelset = HumanoidModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION)
            .map(p_420821_ -> LayerDefinition.create(p_420821_, 64, 32));
        ArmorModelSet<LayerDefinition> armormodelset1 = armormodelset.map(p_420819_ -> p_420819_.apply(HumanoidModel.BABY_TRANSFORMER));
        ArmorModelSet<LayerDefinition> armormodelset2 = PlayerModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION)
            .map(p_420824_ -> LayerDefinition.create(p_420824_, 64, 32));
        ArmorModelSet<LayerDefinition> armormodelset3 = PiglinModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, new CubeDeformation(1.02F))
            .map(p_420818_ -> LayerDefinition.create(p_420818_, 64, 32));
        ArmorModelSet<LayerDefinition> armormodelset4 = armormodelset3.map(p_420827_ -> p_420827_.apply(HumanoidModel.BABY_TRANSFORMER));
        LayerDefinition layerdefinition1 = MinecartModel.createBodyLayer();
        LayerDefinition layerdefinition2 = SkullModel.createMobHeadLayer();
        LayerDefinition layerdefinition3 = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerdefinition4 = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerdefinition5 = EquineSaddleModel.createSaddleLayer(false);
        LayerDefinition layerdefinition6 = EquineSaddleModel.createSaddleLayer(true);
        MeshTransformer meshtransformer = MeshTransformer.scaling(0.9375F);
        LayerDefinition layerdefinition7 = IllagerModel.createBodyLayer().apply(meshtransformer);
        LayerDefinition layerdefinition8 = AxolotlModel.createBodyLayer();
        LayerDefinition layerdefinition9 = BeeModel.createBodyLayer();
        LayerDefinition layerdefinition10 = CowModel.createBodyLayer();
        LayerDefinition layerdefinition11 = ColdChickenModel.createBodyLayer();
        LayerDefinition layerdefinition12 = ColdCowModel.createBodyLayer();
        LayerDefinition layerdefinition13 = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerdefinition14 = ElytraModel.createLayer();
        LayerDefinition layerdefinition15 = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition layerdefinition16 = layerdefinition15.apply(FelineModel.BABY_TRANSFORMER);
        LayerDefinition layerdefinition17 = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32);
        LayerDefinition layerdefinition18 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerdefinition19 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
        LayerDefinition layerdefinition20 = SkullModel.createHumanoidHeadLayer();
        LayerDefinition layerdefinition21 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerdefinition22 = LlamaModel.createBodyLayer(new CubeDeformation(0.5F));
        LayerDefinition layerdefinition23 = StriderModel.createBodyLayer();
        LayerDefinition layerdefinition24 = HoglinModel.createBodyLayer();
        LayerDefinition layerdefinition25 = HoglinModel.createBabyLayer();
        LayerDefinition layerdefinition26 = SkeletonModel.createBodyLayer();
        LayerDefinition layerdefinition27 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(meshtransformer);
        LayerDefinition layerdefinition28 = LayerDefinition.create(VillagerModel.createNoHatModel(), 64, 64).apply(meshtransformer);
        LayerDefinition layerdefinition29 = SpiderModel.createSpiderBodyLayer();
        LayerDefinition layerdefinition30 = ArmadilloModel.createBodyLayer();
        LayerDefinition layerdefinition31 = CamelModel.createBodyLayer();
        LayerDefinition layerdefinition32 = CamelSaddleModel.createSaddleLayer();
        LayerDefinition layerdefinition33 = ChickenModel.createBodyLayer();
        LayerDefinition layerdefinition34 = GoatModel.createBodyLayer();
        LayerDefinition layerdefinition35 = PandaModel.createBodyLayer();
        LayerDefinition layerdefinition36 = PigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerdefinition37 = PigModel.createBodyLayer(new CubeDeformation(0.5F));
        LayerDefinition layerdefinition38 = SheepModel.createBodyLayer();
        LayerDefinition layerdefinition39 = SheepFurModel.createFurLayer();
        LayerDefinition layerdefinition40 = SnifferModel.createBodyLayer();
        LayerDefinition layerdefinition41 = TurtleModel.createBodyLayer();
        LayerDefinition layerdefinition42 = WarmCowModel.createBodyLayer();
        LayerDefinition layerdefinition43 = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
        LayerDefinition layerdefinition44 = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2F)), 64, 32);
        LayerDefinition layerdefinition45 = ZombieVillagerModel.createBodyLayer();
        LayerDefinition layerdefinition46 = ZombieVillagerModel.createNoHatLayer();
        LayerDefinition layerdefinition47 = ArmorStandModel.createBodyLayer();
        ArmorModelSet<LayerDefinition> armormodelset5 = ArmorStandArmorModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
        LayerDefinition layerdefinition48 = DrownedModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerdefinition49 = DrownedModel.createBodyLayer(new CubeDeformation(0.25F));
        LayerDefinition layerdefinition50 = SquidModel.createBodyLayer();
        LayerDefinition layerdefinition51 = DolphinModel.createBodyLayer();
        LayerDefinition layerdefinition52 = SalmonModel.createBodyLayer();
        LayerDefinition layerdefinition53 = NautilusSaddleModel.createSaddleLayer();
        builder.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
        builder.put(ModelLayers.ARMADILLO, layerdefinition30);
        builder.put(ModelLayers.ARMADILLO_BABY, layerdefinition30.apply(ArmadilloModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.ARMOR_STAND, layerdefinition47);
        ModelLayers.ARMOR_STAND_ARMOR.putFrom(armormodelset5, builder);
        builder.put(ModelLayers.ARMOR_STAND_SMALL, layerdefinition47.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ARMOR_STAND_SMALL_ARMOR.putFrom(armormodelset5.map(p_420828_ -> p_420828_.apply(HumanoidModel.BABY_TRANSFORMER)), builder);
        builder.put(ModelLayers.ARROW, ArrowModel.createBodyLayer());
        builder.put(ModelLayers.AXOLOTL, layerdefinition8);
        builder.put(ModelLayers.AXOLOTL_BABY, layerdefinition8.apply(AxolotlModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.STANDING_BANNER, BannerModel.createBodyLayer(true));
        builder.put(ModelLayers.WALL_BANNER, BannerModel.createBodyLayer(false));
        builder.put(ModelLayers.STANDING_BANNER_FLAG, BannerFlagModel.createFlagLayer(true));
        builder.put(ModelLayers.WALL_BANNER_FLAG, BannerFlagModel.createFlagLayer(false));
        builder.put(ModelLayers.BAT, BatModel.createBodyLayer());
        builder.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
        builder.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
        builder.put(ModelLayers.BEE, layerdefinition9);
        builder.put(ModelLayers.BEE_BABY, layerdefinition9.apply(BeeModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.BEE_STINGER, BeeStingerModel.createBodyLayer());
        builder.put(ModelLayers.BELL, BellModel.createBodyLayer());
        builder.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
        builder.put(ModelLayers.BOAT_WATER_PATCH, BoatModel.createWaterPatch());
        builder.put(ModelLayers.BOGGED, BoggedModel.createBodyLayer());
        ModelLayers.BOGGED_ARMOR.putFrom(armormodelset, builder);
        builder.put(ModelLayers.BOGGED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2F), 0.0F), 64, 32));
        builder.put(ModelLayers.BOOK, BookModel.createBodyLayer());
        builder.put(ModelLayers.BREEZE, BreezeModel.createBodyLayer());
        builder.put(ModelLayers.BREEZE_WIND, BreezeModel.createWindLayer());
        builder.put(ModelLayers.BREEZE_EYES, BreezeModel.createEyesLayer());
        builder.put(ModelLayers.CAT, layerdefinition15.apply(CatModel.CAT_TRANSFORMER));
        builder.put(ModelLayers.CAT_BABY, layerdefinition16.apply(CatModel.CAT_TRANSFORMER));
        builder.put(ModelLayers.CAT_COLLAR, layerdefinition17.apply(CatModel.CAT_TRANSFORMER));
        builder.put(ModelLayers.CAT_BABY_COLLAR, layerdefinition17.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
        builder.put(ModelLayers.CAMEL, layerdefinition31);
        builder.put(ModelLayers.CAMEL_BABY, layerdefinition31.apply(CamelModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.CAMEL_SADDLE, layerdefinition32);
        builder.put(ModelLayers.CAMEL_BABY_SADDLE, layerdefinition32.apply(CamelModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.CAMEL_HUSK_SADDLE, layerdefinition32);
        builder.put(ModelLayers.CAMEL_HUSK_BABY_SADDLE, layerdefinition32.apply(CamelModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.CAVE_SPIDER, layerdefinition29.apply(MeshTransformer.scaling(0.7F)));
        builder.put(ModelLayers.CHEST, ChestModel.createSingleBodyLayer());
        builder.put(ModelLayers.CHEST_MINECART, layerdefinition1);
        builder.put(ModelLayers.CHICKEN, layerdefinition33);
        builder.put(ModelLayers.CHICKEN_BABY, layerdefinition33.apply(ChickenModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.COD, CodModel.createBodyLayer());
        builder.put(ModelLayers.COLD_CHICKEN, layerdefinition11);
        builder.put(ModelLayers.COLD_CHICKEN_BABY, layerdefinition11.apply(ChickenModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.COLD_COW, layerdefinition12);
        builder.put(ModelLayers.COLD_COW_BABY, layerdefinition12.apply(CowModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.COLD_PIG, layerdefinition13);
        builder.put(ModelLayers.COLD_PIG_BABY, layerdefinition13.apply(PigModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.COMMAND_BLOCK_MINECART, layerdefinition1);
        builder.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
        builder.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
        builder.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
        builder.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
        builder.put(ModelLayers.COPPER_GOLEM, CopperGolemModel.createBodyLayer());
        builder.put(ModelLayers.COPPER_GOLEM_EYES, CopperGolemModel.createEyesLayer());
        builder.put(ModelLayers.COPPER_GOLEM_RUNNING, CopperGolemModel.createRunningPoseBodyLayer());
        builder.put(ModelLayers.COPPER_GOLEM_SITTING, CopperGolemModel.createSittingPoseBodyLayer());
        builder.put(ModelLayers.COPPER_GOLEM_STAR, CopperGolemModel.createStarPoseBodyLayer());
        builder.put(ModelLayers.COW, layerdefinition10);
        builder.put(ModelLayers.COW_BABY, layerdefinition10.apply(CowModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.CREAKING, CreakingModel.createBodyLayer());
        builder.put(ModelLayers.CREAKING_EYES, CreakingModel.createEyesLayer());
        builder.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
        builder.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
        builder.put(ModelLayers.CREEPER_HEAD, layerdefinition2);
        builder.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
        builder.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
        builder.put(ModelLayers.DOLPHIN, layerdefinition51);
        builder.put(ModelLayers.DOLPHIN_BABY, layerdefinition51.apply(DolphinModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.DONKEY, DonkeyModel.createBodyLayer(0.87F));
        builder.put(ModelLayers.DONKEY_BABY, DonkeyModel.createBabyLayer(0.87F));
        builder.put(ModelLayers.DONKEY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, false));
        builder.put(ModelLayers.DONKEY_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, true));
        builder.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestModel.createDoubleBodyLeftLayer());
        builder.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestModel.createDoubleBodyRightLayer());
        builder.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
        builder.put(ModelLayers.DROWNED, layerdefinition48);
        ModelLayers.DROWNED_ARMOR.putFrom(armormodelset, builder);
        builder.put(ModelLayers.DROWNED_OUTER_LAYER, layerdefinition49);
        builder.put(ModelLayers.DROWNED_BABY, layerdefinition48.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.DROWNED_BABY_ARMOR.putFrom(armormodelset1, builder);
        builder.put(ModelLayers.DROWNED_BABY_OUTER_LAYER, layerdefinition49.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createElderGuardianLayer());
        builder.put(ModelLayers.ELYTRA, layerdefinition14);
        builder.put(ModelLayers.ELYTRA_BABY, layerdefinition14.apply(ElytraModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
        builder.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
        builder.put(ModelLayers.ENDER_DRAGON, EnderDragonModel.createBodyLayer());
        builder.put(ModelLayers.END_CRYSTAL, EndCrystalModel.createBodyLayer());
        builder.put(ModelLayers.EVOKER, layerdefinition7);
        builder.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
        builder.put(ModelLayers.FOX, FoxModel.createBodyLayer());
        builder.put(ModelLayers.FOX_BABY, FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.FROG, FrogModel.createBodyLayer());
        builder.put(ModelLayers.FURNACE_MINECART, layerdefinition1);
        builder.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
        MeshTransformer meshtransformer1 = MeshTransformer.scaling(6.0F);
        builder.put(ModelLayers.GIANT, layerdefinition.apply(meshtransformer1));
        ModelLayers.GIANT_ARMOR.putFrom(armormodelset.map(p_420815_ -> p_420815_.apply(meshtransformer1)), builder);
        builder.put(ModelLayers.GLOW_SQUID, layerdefinition50);
        builder.put(ModelLayers.GLOW_SQUID_BABY, layerdefinition50.apply(SquidModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.GOAT, layerdefinition34);
        builder.put(ModelLayers.GOAT_BABY, layerdefinition34.apply(GoatModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
        builder.put(ModelLayers.HAPPY_GHAST, HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
        builder.put(ModelLayers.HAPPY_GHAST_BABY, HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.HAPPY_GHAST_HARNESS, HappyGhastHarnessModel.createHarnessLayer(false));
        builder.put(ModelLayers.HAPPY_GHAST_BABY_HARNESS, HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.HAPPY_GHAST_ROPES, HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2F)));
        builder.put(ModelLayers.HAPPY_GHAST_BABY_ROPES, HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2F)).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.HOGLIN, layerdefinition24);
        builder.put(ModelLayers.HOGLIN_BABY, layerdefinition25);
        builder.put(ModelLayers.HOPPER_MINECART, layerdefinition1);
        MeshTransformer meshtransformer2 = MeshTransformer.scaling(1.1F);
        builder.put(ModelLayers.HORSE, layerdefinition3.apply(meshtransformer2));
        builder.put(ModelLayers.HORSE_BABY, layerdefinition4.apply(meshtransformer2));
        builder.put(
            ModelLayers.HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64).apply(meshtransformer2)
        );
        builder.put(
            ModelLayers.HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64).apply(meshtransformer2)
        );
        builder.put(ModelLayers.HORSE_SADDLE, layerdefinition5.apply(meshtransformer2));
        builder.put(ModelLayers.HORSE_BABY_SADDLE, layerdefinition6.apply(meshtransformer2));
        MeshTransformer meshtransformer3 = MeshTransformer.scaling(1.0625F);
        builder.put(ModelLayers.HUSK, layerdefinition.apply(meshtransformer3));
        ModelLayers.HUSK_ARMOR.putFrom(armormodelset.map(p_420826_ -> p_420826_.apply(meshtransformer3)), builder);
        builder.put(ModelLayers.HUSK_BABY, layerdefinition.apply(HumanoidModel.BABY_TRANSFORMER).apply(meshtransformer3));
        ModelLayers.HUSK_BABY_ARMOR.putFrom(armormodelset1.map(p_420823_ -> p_420823_.apply(meshtransformer3)), builder);
        builder.put(ModelLayers.ILLUSIONER, layerdefinition7);
        builder.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
        builder.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
        builder.put(ModelLayers.LLAMA, layerdefinition21);
        builder.put(ModelLayers.LLAMA_BABY, layerdefinition21.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.LLAMA_DECOR, layerdefinition22);
        builder.put(ModelLayers.LLAMA_BABY_DECOR, layerdefinition22.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
        builder.put(ModelLayers.MAGMA_CUBE, MagmaCubeModel.createBodyLayer());
        builder.put(ModelLayers.MINECART, layerdefinition1);
        builder.put(ModelLayers.MOOSHROOM, layerdefinition10);
        builder.put(ModelLayers.MOOSHROOM_BABY, layerdefinition10.apply(CowModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.MULE, DonkeyModel.createBodyLayer(0.92F));
        builder.put(ModelLayers.MULE_BABY, DonkeyModel.createBabyLayer(0.92F));
        builder.put(ModelLayers.MULE_SADDLE, DonkeyModel.createSaddleLayer(0.92F, false));
        builder.put(ModelLayers.MULE_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.92F, true));
        builder.put(ModelLayers.NAUTILUS, NautilusModel.createBodyLayer());
        builder.put(ModelLayers.NAUTILUS_BABY, NautilusModel.createBabyBodyLayer());
        builder.put(ModelLayers.NAUTILUS_SADDLE, layerdefinition53);
        builder.put(ModelLayers.NAUTILUS_ARMOR, NautilusArmorModel.createBodyLayer());
        builder.put(ModelLayers.ZOMBIE_NAUTILUS, NautilusModel.createBodyLayer());
        builder.put(ModelLayers.ZOMBIE_NAUTILUS_CORAL, ZombieNautilusCoralModel.createBodyLayer());
        builder.put(ModelLayers.OCELOT, layerdefinition15);
        builder.put(ModelLayers.OCELOT_BABY, layerdefinition16);
        builder.put(ModelLayers.PANDA, layerdefinition35);
        builder.put(ModelLayers.PANDA_BABY, layerdefinition35.apply(PandaModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.PARCHED, SkeletonModel.createSingleModelDualBodyLayer());
        ModelLayers.PARCHED_ARMOR.putFrom(armormodelset, builder);
        builder.put(ModelLayers.PARCHED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
        builder.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
        builder.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
        builder.put(ModelLayers.PIG, layerdefinition36);
        builder.put(ModelLayers.PIG_BABY, layerdefinition36.apply(PigModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.PIG_SADDLE, layerdefinition37);
        builder.put(ModelLayers.PIG_BABY_SADDLE, layerdefinition37.apply(PigModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.PIGLIN, layerdefinition18);
        ModelLayers.PIGLIN_ARMOR.putFrom(armormodelset3, builder);
        builder.put(ModelLayers.PIGLIN_BRUTE, layerdefinition18);
        ModelLayers.PIGLIN_BRUTE_ARMOR.putFrom(armormodelset3, builder);
        builder.put(ModelLayers.PIGLIN_BABY, layerdefinition18.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.PIGLIN_BABY_ARMOR.putFrom(armormodelset4, builder);
        builder.put(ModelLayers.PIGLIN_HEAD, layerdefinition19);
        builder.put(ModelLayers.PILLAGER, layerdefinition7);
        builder.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
        builder.put(ModelLayers.PLAYER_EARS, PlayerEarsModel.createEarsLayer());
        builder.put(ModelLayers.PLAYER_CAPE, PlayerCapeModel.createCapeLayer());
        builder.put(ModelLayers.PLAYER_HEAD, layerdefinition20);
        ModelLayers.PLAYER_ARMOR.putFrom(armormodelset2, builder);
        builder.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
        ModelLayers.PLAYER_SLIM_ARMOR.putFrom(armormodelset2, builder);
        builder.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectModel.createLayer());
        builder.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer(false));
        builder.put(ModelLayers.POLAR_BEAR_BABY, PolarBearModel.createBodyLayer(true));
        builder.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
        builder.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
        builder.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
        builder.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer(false));
        builder.put(ModelLayers.RABBIT_BABY, RabbitModel.createBodyLayer(true));
        builder.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
        builder.put(ModelLayers.SALMON, layerdefinition52);
        builder.put(ModelLayers.SALMON_SMALL, layerdefinition52.apply(SalmonModel.SMALL_TRANSFORMER));
        builder.put(ModelLayers.SALMON_LARGE, layerdefinition52.apply(SalmonModel.LARGE_TRANSFORMER));
        builder.put(ModelLayers.SHEEP, layerdefinition38);
        builder.put(ModelLayers.SHEEP_BABY, layerdefinition38.apply(SheepModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.SHEEP_WOOL, layerdefinition39);
        builder.put(ModelLayers.SHEEP_BABY_WOOL, layerdefinition39.apply(SheepModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.SHEEP_WOOL_UNDERCOAT, layerdefinition38);
        builder.put(ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, layerdefinition38.apply(SheepModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.SHIELD, ShieldModel.createLayer());
        builder.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
        builder.put(ModelLayers.SHULKER_BOX, ShulkerModel.createBoxLayer());
        builder.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
        builder.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
        builder.put(ModelLayers.SKELETON, layerdefinition26);
        ModelLayers.SKELETON_ARMOR.putFrom(armormodelset, builder);
        builder.put(ModelLayers.SKELETON_HORSE, layerdefinition3);
        builder.put(ModelLayers.SKELETON_HORSE_BABY, layerdefinition4);
        builder.put(ModelLayers.SKELETON_HORSE_SADDLE, layerdefinition5);
        builder.put(ModelLayers.SKELETON_HORSE_BABY_SADDLE, layerdefinition6);
        builder.put(ModelLayers.SKELETON_SKULL, layerdefinition2);
        builder.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
        builder.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
        builder.put(ModelLayers.SNIFFER, layerdefinition40);
        builder.put(ModelLayers.SNIFFER_BABY, layerdefinition40.apply(SnifferModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
        builder.put(ModelLayers.SPAWNER_MINECART, layerdefinition1);
        builder.put(ModelLayers.SPIDER, layerdefinition29);
        builder.put(ModelLayers.SQUID, layerdefinition50);
        builder.put(ModelLayers.SQUID_BABY, layerdefinition50.apply(SquidModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.STRAY, layerdefinition26);
        ModelLayers.STRAY_ARMOR.putFrom(armormodelset, builder);
        builder.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
        builder.put(ModelLayers.STRIDER, layerdefinition23);
        builder.put(ModelLayers.STRIDER_SADDLE, layerdefinition23);
        builder.put(ModelLayers.STRIDER_BABY, layerdefinition23.apply(StriderModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.STRIDER_BABY_SADDLE, layerdefinition23.apply(StriderModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
        builder.put(ModelLayers.TNT_MINECART, layerdefinition1);
        builder.put(ModelLayers.TRADER_LLAMA, layerdefinition21);
        builder.put(ModelLayers.TRADER_LLAMA_BABY, layerdefinition21.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.TRIDENT, TridentModel.createLayer());
        builder.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishLargeModel.createBodyLayer(CubeDeformation.NONE));
        builder.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishLargeModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
        builder.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishSmallModel.createBodyLayer(CubeDeformation.NONE));
        builder.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishSmallModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
        builder.put(ModelLayers.TURTLE, layerdefinition41);
        builder.put(ModelLayers.TURTLE_BABY, layerdefinition41.apply(TurtleModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.UNDEAD_HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
        builder.put(ModelLayers.UNDEAD_HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64));
        builder.put(ModelLayers.VEX, VexModel.createBodyLayer());
        builder.put(ModelLayers.VILLAGER, layerdefinition27);
        builder.put(ModelLayers.VILLAGER_NO_HAT, layerdefinition28);
        builder.put(ModelLayers.VILLAGER_BABY, layerdefinition27.apply(VillagerModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.VILLAGER_BABY_NO_HAT, layerdefinition28.apply(VillagerModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.VINDICATOR, layerdefinition7);
        builder.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
        builder.put(ModelLayers.WARDEN_TENDRILS, WardenModel.createTendrilsLayer());
        builder.put(ModelLayers.WARDEN_HEART, WardenModel.createHeartLayer());
        builder.put(ModelLayers.WARDEN_BIOLUMINESCENT, WardenModel.createBioluminescentLayer());
        builder.put(ModelLayers.WARDEN_PULSATING_SPOTS, WardenModel.createPulsatingSpotsLayer());
        builder.put(ModelLayers.WARM_COW, layerdefinition42);
        builder.put(ModelLayers.WARM_COW_BABY, layerdefinition42.apply(CowModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.WANDERING_TRADER, layerdefinition27);
        builder.put(ModelLayers.WIND_CHARGE, WindChargeModel.createBodyLayer());
        builder.put(ModelLayers.WITCH, WitchModel.createBodyLayer().apply(meshtransformer));
        builder.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        builder.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        builder.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
        MeshTransformer meshtransformer4 = MeshTransformer.scaling(1.2F);
        builder.put(ModelLayers.WITHER_SKELETON, layerdefinition26.apply(meshtransformer4));
        ModelLayers.WITHER_SKELETON_ARMOR.putFrom(armormodelset.map(p_420817_ -> p_420817_.apply(meshtransformer4)), builder);
        builder.put(ModelLayers.WITHER_SKELETON_SKULL, layerdefinition2);
        builder.put(ModelLayers.WOLF, layerdefinition43);
        builder.put(ModelLayers.WOLF_ARMOR, layerdefinition44);
        builder.put(ModelLayers.WOLF_BABY, layerdefinition43.apply(WolfModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.WOLF_BABY_ARMOR, layerdefinition44.apply(WolfModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.ZOGLIN, layerdefinition24);
        builder.put(ModelLayers.ZOGLIN_BABY, layerdefinition25);
        builder.put(ModelLayers.ZOMBIE, layerdefinition);
        ModelLayers.ZOMBIE_ARMOR.putFrom(armormodelset, builder);
        builder.put(ModelLayers.ZOMBIE_BABY, layerdefinition.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ZOMBIE_BABY_ARMOR.putFrom(armormodelset1, builder);
        builder.put(ModelLayers.ZOMBIE_HEAD, layerdefinition20);
        builder.put(ModelLayers.ZOMBIE_HORSE, layerdefinition3);
        builder.put(ModelLayers.ZOMBIE_HORSE_BABY, layerdefinition4);
        builder.put(ModelLayers.ZOMBIE_HORSE_SADDLE, layerdefinition5);
        builder.put(ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, layerdefinition6);
        builder.put(ModelLayers.ZOMBIE_VILLAGER, layerdefinition45);
        builder.put(ModelLayers.ZOMBIE_VILLAGER_NO_HAT, layerdefinition46);
        ArmorModelSet<LayerDefinition> armormodelset6 = ZombieVillagerModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
        ModelLayers.ZOMBIE_VILLAGER_ARMOR.putFrom(armormodelset6, builder);
        builder.put(ModelLayers.ZOMBIE_VILLAGER_BABY, layerdefinition45.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put(ModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, layerdefinition46.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ZOMBIE_VILLAGER_BABY_ARMOR.putFrom(armormodelset6.map(p_420820_ -> p_420820_.apply(HumanoidModel.BABY_TRANSFORMER)), builder);
        builder.put(ModelLayers.ZOMBIFIED_PIGLIN, layerdefinition18);
        ModelLayers.ZOMBIFIED_PIGLIN_ARMOR.putFrom(armormodelset3, builder);
        builder.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY, layerdefinition18.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ZOMBIFIED_PIGLIN_BABY_ARMOR.putFrom(armormodelset4, builder);
        builder.put(ModelLayers.BAMBOO_RAFT, RaftModel.createRaftModel());
        builder.put(ModelLayers.BAMBOO_CHEST_RAFT, RaftModel.createChestRaftModel());
        LayerDefinition layerdefinition54 = BoatModel.createBoatModel();
        LayerDefinition layerdefinition55 = BoatModel.createChestBoatModel();
        builder.put(ModelLayers.OAK_BOAT, layerdefinition54);
        builder.put(ModelLayers.OAK_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.SPRUCE_BOAT, layerdefinition54);
        builder.put(ModelLayers.SPRUCE_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.BIRCH_BOAT, layerdefinition54);
        builder.put(ModelLayers.BIRCH_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.JUNGLE_BOAT, layerdefinition54);
        builder.put(ModelLayers.JUNGLE_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.ACACIA_BOAT, layerdefinition54);
        builder.put(ModelLayers.ACACIA_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.CHERRY_BOAT, layerdefinition54);
        builder.put(ModelLayers.CHERRY_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.DARK_OAK_BOAT, layerdefinition54);
        builder.put(ModelLayers.DARK_OAK_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.PALE_OAK_BOAT, layerdefinition54);
        builder.put(ModelLayers.PALE_OAK_CHEST_BOAT, layerdefinition55);
        builder.put(ModelLayers.MANGROVE_BOAT, layerdefinition54);
        builder.put(ModelLayers.MANGROVE_CHEST_BOAT, layerdefinition55);
        LayerDefinition layerdefinition56 = SignRenderer.createSignLayer(true);
        LayerDefinition layerdefinition57 = SignRenderer.createSignLayer(false);
        WoodType.values().forEach(p_374591_ -> {
            builder.put(ModelLayers.createStandingSignModelName(p_374591_), layerdefinition56);
            builder.put(ModelLayers.createWallSignModelName(p_374591_), layerdefinition57);

            for (HangingSignRenderer.AttachmentType hangingsignrenderer$attachmenttype : HangingSignRenderer.AttachmentType.values()) {
                LayerDefinition layerdefinition58 = HangingSignRenderer.createHangingSignLayer(hangingsignrenderer$attachmenttype);
                builder.put(ModelLayers.createHangingSignModelName(p_374591_, hangingsignrenderer$attachmenttype), layerdefinition58);
            }
        });
        ImmutableMap<ModelLayerLocation, LayerDefinition> immutablemap = builder.build();
        List<ModelLayerLocation> list = ModelLayers.getKnownLocations().filter(p_171117_ -> !immutablemap.containsKey(p_171117_)).toList();
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + list);
        } else {
            return immutablemap;
        }
    }
}